version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: kampung_gatot
    volumes:
      - .:/var/www/html:cached
    depends_on:
      - mysql
    networks:
      - kampung_gatot
    mem_limit: 2g
    cpus: 3

  nginx:
    image: nginx:stable-alpine
    container_name: kampung_gatot_nginx
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - kampung_gatot
    mem_limit: 512m
    cpus: 0.5

  mysql:
    image: mysql:8.0
    container_name: kampung_gatot_mysql
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: db_kampung_gatot
        MYSQL_USER: user
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret # Diperlukan untuk inisialisasi
    ports:
        - "3311:3306"
    volumes:
        - mysql-data:/var/lib/mysql
    networks:
        - kampung_gatot
    mem_limit: 2g
    cpus: 2



  redis:
    image: redis:7-alpine
    container_name: kampung_gatot_redis
    ports:
      - "6379:6379"
    networks:
      - kampung_gatot
    mem_limit: 512m
    cpus: 0.5

networks:
  kampung_gatot:
    driver: bridge

volumes:
  mysql-data:
